### PR TITLE
Feature/disable autoexposure

### PR DESCRIPTION
**Pull request by lorow**
Improves the camera settings a bit, to make the image brighter without oversaturation, it also disables the autoexposure feature making the image less bright than it should be 

additionally - documents the camera settings

### CODE REVIEW

**Comment by ZanzyTHEbar** [comment]
Looks good, i see no issues and it compiles on my side. Should be good to go.

**Review by ZanzyTHEbar — APPROVED** [review]
Looks great :) i don't see anything wrong with this

**Comment by lorow** [comment]
I've been waiting to test it, or for someone to grab it and try it out with the newset version of the app, but eh. It should be fine. My own tests with the esp mounted to the lens-cover in complete darkness showed nothing bad happening to the algos, hell it even tracked way better. Same thing when I shined a flashlight on it, nothing went haywire. 

So, I guess we're ready to merge both of the PRs?

**Comment by lorow** [comment]
I finally had a chance to test it, everything is more than fine, we can merge it!

**Pull request merged**
